package com.diamon.calculo.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Main structural model container. Holds all geometry, materials, loads, and results.
 * Can generate OpenSees TCL and Python scripts from the model data.
 */
public class StructuralModel {
    private List<StructuralNode> nodes;
    private List<FrameElement> elements;
    private List<StructuralMaterial> materials;
    private List<SectionProfile> sections;
    private List<LoadPattern> loadPatterns;
    private AnalysisResult result;

    public StructuralModel() {
        this.nodes = new ArrayList<>();
        this.elements = new ArrayList<>();
        this.materials = new ArrayList<>();
        this.sections = new ArrayList<>();
        this.loadPatterns = new ArrayList<>();
    }

    // Getters
    public List<StructuralNode> getNodes() { return nodes; }
    public List<FrameElement> getElements() { return elements; }
    public List<StructuralMaterial> getMaterials() { return materials; }
    public List<SectionProfile> getSections() { return sections; }
    public List<LoadPattern> getLoadPatterns() { return loadPatterns; }
    public AnalysisResult getResult() { return result; }
    public void setResult(AnalysisResult result) { this.result = result; }

    // Add methods
    public void addNode(StructuralNode node) { nodes.add(node); }
    public void addElement(FrameElement element) { elements.add(element); }
    public void addMaterial(StructuralMaterial material) { materials.add(material); }
    public void addSection(SectionProfile section) { sections.add(section); }
    public void addLoadPattern(LoadPattern pattern) { loadPatterns.add(pattern); }

    /**
     * Generate an OpenSees TCL script from the model definition.
     */
    public String generateTclScript() {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by Structural & Seismic Research\n");
        sb.append("# OpenSees TCL Script\n\n");
        sb.append("wipe\n");

        // Determine NDM and NDF
        boolean is3D = nodes.stream().anyMatch(n -> n.z != 0.0);
        int ndm = is3D ? 3 : 2;
        int ndf = is3D ? 6 : 3;
        sb.append(String.format("model BasicBuilder -ndm %d -ndf %d\n\n", ndm, ndf));

        // Nodes
        sb.append("# --- Nodes ---\n");
        for (StructuralNode node : nodes) {
            if (is3D) {
                sb.append(String.format(Locale.US, "node %d %.4f %.4f %.4f\n",
                        node.id, node.x, node.y, node.z));
            } else {
                sb.append(String.format(Locale.US, "node %d %.4f %.4f\n",
                        node.id, node.x, node.y));
            }
        }
        sb.append("\n");

        // Boundary conditions
        sb.append("# --- Boundary Conditions ---\n");
        for (StructuralNode node : nodes) {
            if (node.fixX || node.fixY || node.fixZ) {
                if (is3D) {
                    sb.append(String.format("fix %d %d %d %d %d %d %d\n", node.id,
                            node.fixX ? 1 : 0, node.fixY ? 1 : 0, node.fixZ ? 1 : 0,
                            node.fixRX ? 1 : 0, node.fixRY ? 1 : 0, node.fixRZ ? 1 : 0));
                } else {
                    sb.append(String.format("fix %d %d %d %d\n", node.id,
                            node.fixX ? 1 : 0, node.fixY ? 1 : 0,
                            node.fixRZ ? 1 : 0));
                }
            }
        }
        sb.append("\n");

        // Geometric transformations
        sb.append("# --- Geometric Transformations ---\n");
        sb.append("geomTransf Linear 1\n\n");

        // Elements
        sb.append("# --- Elements ---\n");
        for (FrameElement elem : elements) {
            StructuralMaterial mat = findMaterial(elem.materialId);
            SectionProfile sec = findSection(elem.sectionId);
            double E = mat != null ? mat.E : 2.0e8;
            double A = sec != null ? sec.area : 0.01;
            double Iz = sec != null ? sec.Iz : 0.0001;
            sb.append(String.format(Locale.US,
                    "element elasticBeamColumn %d %d %d %.6e %.6e %.6e 1\n",
                    elem.id, elem.nodeI, elem.nodeJ, A, E, Iz));
        }
        sb.append("\n");

        // Load patterns
        sb.append("# --- Load Patterns ---\n");
        for (LoadPattern lp : loadPatterns) {
            sb.append(String.format("pattern Plain %d Linear {\n", lp.id));
            if (lp.loads != null) {
                for (NodeLoad nl : lp.loads) {
                    if (is3D) {
                        sb.append(String.format(Locale.US,
                                "    load %d %.4f %.4f %.4f %.4f %.4f %.4f\n",
                                nl.nodeId, nl.fx, nl.fy, nl.fz, nl.mx, nl.my, nl.mz));
                    } else {
                        sb.append(String.format(Locale.US,
                                "    load %d %.4f %.4f %.4f\n",
                                nl.nodeId, nl.fx, nl.fy, nl.mz));
                    }
                }
            }
            sb.append("}\n");
        }
        sb.append("\n");

        // Analysis
        sb.append("# --- Analysis ---\n");
        sb.append("system BandGeneral\n");
        sb.append("numberer RCM\n");
        sb.append("constraints Plain\n");
        sb.append("integrator LoadControl 1.0\n");
        sb.append("algorithm Linear\n");
        sb.append("analysis Static\n");
        sb.append("analyze 1\n\n");

        // Print results
        sb.append("# --- Results ---\n");
        for (StructuralNode node : nodes) {
            if (!node.isFullyFixed()) {
                sb.append(String.format(
                        "puts \"Node %d: Ux=[nodeDisp %d 1] Uy=[nodeDisp %d 2]\"\n",
                        node.id, node.id, node.id));
            }
        }
        sb.append("\nexit\n");
        return sb.toString();
    }

    /**
     * Generate an OpenSeesPy (Python) script from the model definition.
     */
    public String generatePyScript() {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by Structural & Seismic Research\n");
        sb.append("# OpenSeesPy Script\n\n");
        sb.append("import opensees as ops\n\n");
        sb.append("ops.wipe()\n");

        boolean is3D = nodes.stream().anyMatch(n -> n.z != 0.0);
        int ndm = is3D ? 3 : 2;
        int ndf = is3D ? 6 : 3;
        sb.append(String.format("ops.model('basic', '-ndm', %d, '-ndf', %d)\n\n", ndm, ndf));

        // Nodes
        sb.append("# --- Nodes ---\n");
        for (StructuralNode node : nodes) {
            if (is3D) {
                sb.append(String.format(Locale.US, "ops.node(%d, %.4f, %.4f, %.4f)\n",
                        node.id, node.x, node.y, node.z));
            } else {
                sb.append(String.format(Locale.US, "ops.node(%d, %.4f, %.4f)\n",
                        node.id, node.x, node.y));
            }
        }
        sb.append("\n");

        // Boundary conditions
        sb.append("# --- Boundary Conditions ---\n");
        for (StructuralNode node : nodes) {
            if (node.fixX || node.fixY || node.fixZ) {
                if (is3D) {
                    sb.append(String.format("ops.fix(%d, %d, %d, %d, %d, %d, %d)\n", node.id,
                            node.fixX ? 1 : 0, node.fixY ? 1 : 0, node.fixZ ? 1 : 0,
                            node.fixRX ? 1 : 0, node.fixRY ? 1 : 0, node.fixRZ ? 1 : 0));
                } else {
                    sb.append(String.format("ops.fix(%d, %d, %d, %d)\n", node.id,
                            node.fixX ? 1 : 0, node.fixY ? 1 : 0,
                            node.fixRZ ? 1 : 0));
                }
            }
        }
        sb.append("\n");

        // Transformations and elements
        sb.append("# --- Elements ---\n");
        sb.append("ops.geomTransf('Linear', 1)\n");
        for (FrameElement elem : elements) {
            StructuralMaterial mat = findMaterial(elem.materialId);
            SectionProfile sec = findSection(elem.sectionId);
            double E = mat != null ? mat.E : 2.0e8;
            double A = sec != null ? sec.area : 0.01;
            double Iz = sec != null ? sec.Iz : 0.0001;
            sb.append(String.format(Locale.US,
                    "ops.element('elasticBeamColumn', %d, %d, %d, %.6e, %.6e, %.6e, 1)\n",
                    elem.id, elem.nodeI, elem.nodeJ, A, E, Iz));
        }
        sb.append("\n");

        // Load patterns
        sb.append("# --- Load Patterns ---\n");
        sb.append("ops.timeSeries('Linear', 1)\n");
        for (LoadPattern lp : loadPatterns) {
            sb.append(String.format("ops.pattern('Plain', %d, 1)\n", lp.id));
            if (lp.loads != null) {
                for (NodeLoad nl : lp.loads) {
                    if (is3D) {
                        sb.append(String.format(Locale.US,
                                "ops.load(%d, %.4f, %.4f, %.4f, %.4f, %.4f, %.4f)\n",
                                nl.nodeId, nl.fx, nl.fy, nl.fz, nl.mx, nl.my, nl.mz));
                    } else {
                        sb.append(String.format(Locale.US,
                                "ops.load(%d, %.4f, %.4f, %.4f)\n",
                                nl.nodeId, nl.fx, nl.fy, nl.mz));
                    }
                }
            }
        }
        sb.append("\n");

        // Analysis
        sb.append("# --- Analysis ---\n");
        sb.append("ops.system('BandGeneral')\n");
        sb.append("ops.numberer('RCM')\n");
        sb.append("ops.constraints('Plain')\n");
        sb.append("ops.integrator('LoadControl', 1.0)\n");
        sb.append("ops.algorithm('Linear')\n");
        sb.append("ops.analysis('Static')\n");
        sb.append("ops.analyze(1)\n\n");

        // Print results
        sb.append("# --- Results ---\n");
        for (StructuralNode node : nodes) {
            if (!node.isFullyFixed()) {
                sb.append(String.format(
                        "print(f'Node %d: Ux={ops.nodeDisp(%d, 1):.6e} Uy={ops.nodeDisp(%d, 2):.6e}')\n",
                        node.id, node.id, node.id));
            }
        }
        return sb.toString();
    }

    private StructuralMaterial findMaterial(int id) {
        for (StructuralMaterial m : materials) {
            if (m.id == id) return m;
        }
        return null;
    }

    private SectionProfile findSection(int id) {
        for (SectionProfile s : sections) {
            if (s.id == id) return s;
        }
        return null;
    }
}
