package com.diamon.calculo.ui;

import android.os.Bundle;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.graphics.Color;
import android.graphics.Typeface;
import android.util.TypedValue;
import android.view.MenuItem;

/**
 * Privacy Policy activity explaining local-only data processing.
 */
public class PrivacyPolicyActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (getSupportActionBar() != null) {
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            getSupportActionBar().setTitle("Privacy Policy");
        }

        ScrollView scrollView = new ScrollView(this);
        scrollView.setBackgroundColor(Color.parseColor("#121212"));

        LinearLayout layout = new LinearLayout(this);
        layout.setOrientation(LinearLayout.VERTICAL);
        layout.setPadding(48, 48, 48, 48);

        addSection(layout, "Privacy Policy",
                "Structural and Seismic Research (\"the App\") is committed to " +
                "protecting your privacy. This privacy policy explains how the App " +
                "handles information.");

        addSection(layout, "Data Collection",
                "The App does NOT collect, store, or transmit any personal data. " +
                "All structural models, analysis scripts, and computation results " +
                "are processed and stored locally on your device.\n\n" +
                "No data is sent to external servers.\n" +
                "No analytics or tracking services are used.\n" +
                "No user accounts are required.");

        addSection(layout, "Local Data Storage",
                "The App stores the following data locally on your device:\n\n" +
                "• Structural model files (.tcl, .py)\n" +
                "• Analysis results and log files\n" +
                "• PDF reports generated by the user\n" +
                "• Application preferences\n\n" +
                "All data is stored in the App's private storage directory and is " +
                "automatically deleted when the App is uninstalled.");

        addSection(layout, "OpenSees Engine",
                "The OpenSees analysis engine runs entirely on-device. No cloud " +
                "computing or remote processing is involved. All structural " +
                "calculations are performed using the device's local CPU.");

        addSection(layout, "Third-Party Services",
                "The App does not use any third-party services, SDKs, or APIs " +
                "that collect user data.");

        addSection(layout, "Changes to This Policy",
                "We may update this privacy policy from time to time. Any changes " +
                "will be reflected in the App update notes.");

        addSection(layout, "Contact",
                "If you have questions about this privacy policy, please contact " +
                "us at:\n\nhttps://diamon.com/privacy-policy");

        TextView lastUpdated = new TextView(this);
        lastUpdated.setText("Last updated: July 2026");
        lastUpdated.setTextColor(Color.GRAY);
        lastUpdated.setTextSize(TypedValue.COMPLEX_UNIT_SP, 12);
        lastUpdated.setPadding(0, 32, 0, 0);
        layout.addView(lastUpdated);

        scrollView.addView(layout);
        setContentView(scrollView);
    }

    private void addSection(LinearLayout parent, String title, String content) {
        LinearLayout card = new LinearLayout(this);
        card.setOrientation(LinearLayout.VERTICAL);
        card.setBackgroundColor(Color.parseColor("#1E1E1E"));
        card.setPadding(32, 24, 32, 24);
        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT);
        params.setMargins(0, 16, 0, 0);
        card.setLayoutParams(params);

        TextView tvTitle = new TextView(this);
        tvTitle.setText(title);
        tvTitle.setTextSize(TypedValue.COMPLEX_UNIT_SP, 16);
        tvTitle.setTextColor(Color.parseColor("#64B5F6"));
        tvTitle.setTypeface(Typeface.DEFAULT_BOLD);
        tvTitle.setPadding(0, 0, 0, 12);
        card.addView(tvTitle);

        TextView tvContent = new TextView(this);
        tvContent.setText(content);
        tvContent.setTextSize(TypedValue.COMPLEX_UNIT_SP, 13);
        tvContent.setTextColor(Color.parseColor("#E0E0E0"));
        card.addView(tvContent);

        parent.addView(card);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == android.R.id.home) {
            finish();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
}
